#ifndef __STICKMATCH_ACTOR_HPP__
#define __STICKMATCH_ACTOR_HPP__

#include <System/DataTypes.hpp>

namespace StickMatch
{
	const ZED_FLOAT32 ACTOR_MOVE_VELOCITY_MIN = -2.0f;
	const ZED_FLOAT32 ACTOR_MOVE_VELOCITY_MAX = 2.0f;

	typedef enum ACTOR_MOVE_DIRECTION
	{
		ACTOR_MOVE_DIRECTION_MIN = 0,
		ACTOR_MOVE_DIRECTION_UP,
		ACTOR_MOVE_DIRECTION_DOWN,
		ACTOR_MOVE_DIRECTION_LEFT,
		ACTOR_MOVE_DIRECTION_RIGHT,
		ACTOR_MOVE_DIRECTION_MAX
	};
}

#endif

